# Generated by Django 3.0.8 on 2020-08-02 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('active', 'Active'), ('in_active', 'In active')], max_length=100)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('desc', tinymce.models.HTMLField(default='')),
                ('pub_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('answer_count', models.IntegerField(default=0)),
                ('viewed', models.IntegerField(default=0)),
                ('like_count', models.IntegerField(default=0)),
                ('unlike_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('checking', 'Checking'), ('waiting', 'Waiting'), ('completed', 'Completed')], default='checking', max_length=100)),
                ('tags', models.ManyToManyField(to='question.Tag')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
